### PR TITLE
Rename export for node to PostHog

### PR DESCRIPTION
**Pull request by mariusandra**
No more `PostHogGlobal`

### CODE REVIEW

**Review by benjackwhite — APPROVED** [review]
lgtm but didnt check locally

**Comment by neilkakkar** [comment]
Tested locally: Works for `cjs`.

When a module though, we need to `import {PostHog} from 'posthog-node'`. I'm guessing something to do with default imports not existing for modules?

**Comment by mariusandra** [comment]
What if we just kill the default export? It's bad practice anyway, and people are willing to change code when they upgrade to a new major version like 2.0.

**Comment by neilkakkar** [comment]
Sounds good to me

**Pull request merged**
